treatments:
  - name: solo_easy
    factorIds:
      - h2BqhGfheRcqrQsWN
      - qL8h26YncBQyJA7fq
      - 3kYYXaky46XwqCqs3
      - MdzxCgDh5rZyYt4S7
      - JbazebYNtuWevZQvP
      - i2Ca8myYtMDRjCJHw
      - 3oGEScooi2BhsEKEP
      - 2YsCrAijbvTAMMo8z
      - GNXTq424wgxMYAiNb
      - NTaYAj5MWigZGWAL9
      - g4vPNzQeMfEC6Eafg
      - gybtznggn9JBgfQM7
      - 3ahp7KyDHp4KQCcM6
      - ZKZzcciefoHq5qQ23
  - name: solo_medium
    factorIds:
      - h2BqhGfheRcqrQsWN
      - qL8h26YncBQyJA7fq
      - 3kYYXaky46XwqCqs3
      - MdzxCgDh5rZyYt4S7
      - JbazebYNtuWevZQvP
      - i2Ca8myYtMDRjCJHw
      - 3oGEScooi2BhsEKEP
      - 2YsCrAijbvTAMMo8z
      - GNXTq424wgxMYAiNb
      - NTaYAj5MWigZGWAL9
      - g4vPNzQeMfEC6Eafg
      - 54Hh2E3JdukMpJWWP
      - 3ahp7KyDHp4KQCcM6
      - ZKZzcciefoHq5qQ23
  - name: solo_hard
    factorIds:
      - h2BqhGfheRcqrQsWN
      - qL8h26YncBQyJA7fq
      - 3kYYXaky46XwqCqs3
      - MdzxCgDh5rZyYt4S7
      - JbazebYNtuWevZQvP
      - i2Ca8myYtMDRjCJHw
      - 3oGEScooi2BhsEKEP
      - 2YsCrAijbvTAMMo8z
      - GNXTq424wgxMYAiNb
      - NTaYAj5MWigZGWAL9
      - g4vPNzQeMfEC6Eafg
      - 33b9MJNdBgJky6XiE
      - 3ahp7KyDHp4KQCcM6
      - ZKZzcciefoHq5qQ23
  - name: dynamic_no_feedback
    factorIds:
      - 9ssjc26yHDZM2nYnx
      - qL8h26YncBQyJA7fq
      - ekcnsAf3Y3jvvqTGb
      - MdzxCgDh5rZyYt4S7
      - HDjyRQ4qbgPvk8fzx
      - i2Ca8myYtMDRjCJHw
      - 3oGEScooi2BhsEKEP
      - 2YsCrAijbvTAMMo8z
      - GNXTq424wgxMYAiNb
      - NTaYAj5MWigZGWAL9
      - g4vPNzQeMfEC6Eafg
      - uo5hoxgHYWRGuG4oR
      - 3ahp7KyDHp4KQCcM6
      - i96zebYbj85gRQ73R
  - name: dynamic_self_feedback
    factorIds:
      - 9ssjc26yHDZM2nYnx
      - qL8h26YncBQyJA7fq
      - ekcnsAf3Y3jvvqTGb
      - MdzxCgDh5rZyYt4S7
      - HDjyRQ4qbgPvk8fzx
      - CCuSfLovDqt7gGu8M
      - 3oGEScooi2BhsEKEP
      - 2YsCrAijbvTAMMo8z
      - GNXTq424wgxMYAiNb
      - w5h78Y8ez9KcWJPDt
      - g4vPNzQeMfEC6Eafg
      - uo5hoxgHYWRGuG4oR
      - 3ahp7KyDHp4KQCcM6
      - kdg6ZCYs5xCkft9cd
  - name: dynamic_full_feedback
    factorIds:
      - 9ssjc26yHDZM2nYnx
      - qL8h26YncBQyJA7fq
      - ekcnsAf3Y3jvvqTGb
      - MdzxCgDh5rZyYt4S7
      - HDjyRQ4qbgPvk8fzx
      - CCuSfLovDqt7gGu8M
      - 3oGEScooi2BhsEKEP
      - 2YsCrAijbvTAMMo8z
      - GNXTq424wgxMYAiNb
      - w5h78Y8ez9KcWJPDt
      - HSWXdFt73zaGhGrsj
      - uo5hoxgHYWRGuG4oR
      - 3ahp7KyDHp4KQCcM6
      - pgmME9h2NpvnthfbP
factorTypes:
  - _id: zbBiXuE5R3SySQH4o
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: ra5PM875WMvEnppGS
    name: botsCount
    description: The Number of bots that should participate in a given game
    required: false
    type: Number
    min: 0
    max: 100
  - _id: 7xNFGv5WCZAXxjZKc
    name: altersCount
    description: The Number of connections for each player
    required: true
    type: Integer
    min: 0
    max: 50
  - _id: QzogBfgatZr8JuAP3
    name: stageDuration
    description: The maximum time in seconds for each stage before moving to the next
    required: true
    type: Integer
    min: 5
    max: 60
  - _id: wAD8GzhvbTy4wHimY
    name: rewiring
    description: Can the player change their alters on each round
    required: true
    type: Boolean
  - _id: 8gqCENQ45X9KBWhgS
    name: feedbackRate
    description: how frequent the feedback is (1 = every round; 0 = never)
    required: true
    type: Number
    min: 0
    max: 1
  - _id: QGXdyRSPsEnjDNqNW
    name: feedbackNoise
    description: The level of noise added to performance of the alters
    required: false
    type: Number
    min: 0
    max: 1
  - _id: nixpWHDsnQ9TeEZrQ
    name: shockRate
    description: The rate at which we change difficulties for the players
    required: true
    type: Number
    min: 0
    max: 1
  - _id: ivryKtaipqLtfguqP
    name: nRounds
    description: This is the number of rounds for the game
    required: true
    type: Integer
    min: 1
    max: 20
  - _id: Cp75drvkuSL2jeiMW
    name: selfFeedback
    description: whether to show feedback about one's performance
    required: false
    type: Boolean
  - _id: Cp15drvkuSL3jEiWw
    name: peersFeedback
    description: whether to show feedback about one's peers
    required: false
    type: Boolean
  - _id: AcPdcacgL6Yt9dir5
    name: difficultyTypes
    description: how to distribute difficulties across players
    required: false
    type: String
    min: 1
    max: 100
  - _id: pTddCTs4F5i76Ps2u
    name: basePay
    description: how much to pay them for participating in the expeirment
    required: false
    type: Number
    min: 0
    max: 100
  - _id: 5hKau3zXYmnKyezQ8
    name: conversionRate
    description: the factor that converts game points into real dollar money
    required: true
    type: Number
    min: 0
    max: 1
factors:
  - _id: HDjyRQ4qbgPvk8fzx
    name: 'true'
    value: true
    factorTypeId: wAD8GzhvbTy4wHimY
  - _id: JbazebYNtuWevZQvP
    name: 'false'
    value: false
    factorTypeId: wAD8GzhvbTy4wHimY
  - _id: w5h78Y8ez9KcWJPDt
    name: 'true'
    value: true
    factorTypeId: Cp75drvkuSL2jeiMW
  - _id: NTaYAj5MWigZGWAL9
    name: 'false'
    value: false
    factorTypeId: Cp75drvkuSL2jeiMW
  - _id: HSWXdFt73zaGhGrsj
    name: 'true'
    value: true
    factorTypeId: Cp15drvkuSL3jEiWw
  - _id: g4vPNzQeMfEC6Eafg
    name: 'false'
    value: false
    factorTypeId: Cp15drvkuSL3jEiWw
  - _id: h2BqhGfheRcqrQsWN
    name: solo
    value: 1
    factorTypeId: zbBiXuE5R3SySQH4o
  - _id: 9ssjc26yHDZM2nYnx
    name: group
    value: 12
    factorTypeId: zbBiXuE5R3SySQH4o
  - _id: qL8h26YncBQyJA7fq
    name: none
    value: 0
    factorTypeId: ra5PM875WMvEnppGS
  - _id: 3kYYXaky46XwqCqs3
    name: no_social
    value: 0
    factorTypeId: 7xNFGv5WCZAXxjZKc
  - _id: ekcnsAf3Y3jvvqTGb
    name: small_social
    value: 3
    factorTypeId: 7xNFGv5WCZAXxjZKc
  - _id: MdzxCgDh5rZyYt4S7
    name: 30s
    value: 30
    factorTypeId: QzogBfgatZr8JuAP3
  - _id: CCuSfLovDqt7gGu8M
    name: always
    value: 1
    factorTypeId: 8gqCENQ45X9KBWhgS
  - _id: i2Ca8myYtMDRjCJHw
    name: never
    value: 0
    factorTypeId: 8gqCENQ45X9KBWhgS
  - _id: 3oGEScooi2BhsEKEP
    name: none
    value: 0
    factorTypeId: QGXdyRSPsEnjDNqNW
  - _id: 2YsCrAijbvTAMMo8z
    name: rare
    value: 0.1
    factorTypeId: nixpWHDsnQ9TeEZrQ
  - _id: GNXTq424wgxMYAiNb
    name: full_game
    value: 20
    factorTypeId: ivryKtaipqLtfguqP
  - _id: gybtznggn9JBgfQM7
    name: all_easy
    value: easy
    factorTypeId: AcPdcacgL6Yt9dir5
  - _id: 33b9MJNdBgJky6XiE
    name: all_hard
    value: hard
    factorTypeId: AcPdcacgL6Yt9dir5
  - _id: 54Hh2E3JdukMpJWWP
    name: all_medium
    value: medium
    factorTypeId: AcPdcacgL6Yt9dir5
  - _id: uo5hoxgHYWRGuG4oR
    name: equal_mix
    value: equal_mix
    factorTypeId: AcPdcacgL6Yt9dir5
  - _id: 3ahp7KyDHp4KQCcM6
    name: '2'
    value: 2
    factorTypeId: pTddCTs4F5i76Ps2u
  - _id: ZKZzcciefoHq5qQ23
    name: '0.01'
    value: 0.01
    factorTypeId: 5hKau3zXYmnKyezQ8
  - _id: pgmME9h2NpvnthfbP
    name: '0.03'
    value: 0.03
    factorTypeId: 5hKau3zXYmnKyezQ8
  - _id: kdg6ZCYs5xCkft9cd
    name: '0.035'
    value: 0.035
    factorTypeId: 5hKau3zXYmnKyezQ8
  - _id: i96zebYbj85gRQ73R
    name: '0.037'
    value: 0.037
    factorTypeId: 5hKau3zXYmnKyezQ8
  - _id: iS6ggGpJRwQ8zYLnQ
    name: random
    value: random
    factorTypeId: AcPdcacgL6Yt9dir5
lobbyConfigs:
  - timeoutType: lobby
    timeoutInSeconds: 600
    timeoutStrategy: fail
    gameLobbyIds: []
